apiVersion: v1
kind: Service
metadata:
  name: yatc-postgres
  labels:
    app: yatc-postgres
spec:
  type: ClusterIP
  selector:
    app: yatc-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
