apiVersion: v1
kind: Service
metadata:
  name: yatc-postgres-exporter
  labels:
    app: yatc-postgres-exporter
spec:
  type: ClusterIP
  selector:
    app: yatc-postgres-exporter
  ports:
    - name: postgres-exporter
      protocol: TCP
      port: 9187
      targetPort: 9187
