apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yatc-alloy
  labels:
    yatc-alloy
spec:
  selector:
    matchLabels:
      app: yatc-alloy
  template:
    metadata:
      labels:
        app: yatc-alloy
    spec:
      serviceAccountName: default
      containers:
        - name: yatc-alloy
          image: grafana/alloy:v1.10.0
          imagePullPolicy: Never
          args:
            - --config.file=/etc/alloy/alloy-config.yaml
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
