apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yatc-alloy
  labels:
    app: yatc-alloy
spec:
  selector:
    matchLabels:
      app: yatc-alloy
  template:
    metadata:
      labels:
        app: yatc-alloy
    spec:
      serviceAccountName: yatc-alloy
      containers:
        - name: yatc-alloy
          image: grafana/alloy:v1.11.0
          imagePullPolicy: IfNotPresent
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - /etc/alloy/yatc-alloy-config.alloy
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
          ports:
          - containerPort: 12345
          livenessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          env:
          - name: "TZ"
            value: "Europe/Rome"
          volumeMounts:
          - name: config
            mountPath: "/etc/alloy/yatc-alloy-config.alloy"
            subPath: "yatc-alloy-config.alloy"
      volumes:
      - name: config
        configMap:
          name: yatc-alloy-config
