apiVersion: v1
kind: Service
metadata:
  name: yatc-alloy
  labels:
    app: yatc-alloy
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '12345'
spec:
  type: ClusterIP
  selector:
    app: yatc-alloy
  ports:
    - name: yatc-alloy
      protocol: TCP
      port: 12345
      targetPort: 12345
