FROM node:24-alpine

# Impostazione timezone di default
RUN apk add --no-cache tzdata
ENV TZ="Europe/Rome"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --omit=dev
COPY ./dist ./

EXPOSE 4001
EXPOSE 8080

RUN addgroup -S yatcusr && adduser -S yatcusr -G yatcusr
USER yatcusr

ENTRYPOINT ["node","./app.js"]
