# for production

FROM node:22-alpine
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --only=production
COPY ./dist ./

EXPOSE 4001
EXPOSE 8080

ENTRYPOINT ["node","./app.js"]
