# for production

FROM node:24-alpine
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --omit=dev
COPY ./dist ./

EXPOSE 4001
EXPOSE 8080

RUN addgroup -S yatcusr && adduser -S yatcusr -G yatcusr
USER yatcusr

ENTRYPOINT ["node","./app.js"]
