apiVersion: v1
kind: Service
metadata:
  name: fe-angular-material
  labels:
    app: fe-angular-material
#  annotations:
#    prometheus.io/scrape: 'true'
#    prometheus.io/path: '/actuator/prometheus'
#    prometheus.io/port: '18080'
spec:
  type: ClusterIP
  selector:
    app: fe-angular-material
  ports:
    - name: fe-angular-material
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: fe-angular-material-monitor
      protocol: TCP
      port: 8080
      targetPort: 8080
