apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-support-pod
  labels:
    app: yatc-support-pod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-support-pod
  template:
    metadata:
      labels:
        app: yatc-support-pod
    spec:
      containers:
      - name: yatc-support-pod
        image: nginx:bookworm
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 80
        env:
        - name: "TZ"
          value: "Europe/Rome"
