name: yatc-project

services:
  ms-rest-axum:
    build: ./ms-rust-axum
    restart: no
    container_name: "ms-rest-axum"
    ports:
      - 8080:8080
    networks:
      - yatc-network

  yatc-redis:
    image: redis:7
    restart: no
    container_name: "yatc-redis"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - yatc-network

networks: 
  yatc-network:
    driver: bridge
