name: yatc-project

services:
  ms-rest-axum:
    build: ./ms-rust-axum
    container_name: "ms-rest-axum"
    restart: no
    ports:
      - 8080:8080
    networks:
      - yatc-network

networks: 
  yatc-network:
    driver: bridge
