name: yatc-project

services:
  gw-spring-cloud:
    build: ./gw-spring-cloud
    restart: no
    container_name: "gw-spring-cloud"
    ports:
    - 8080:8080
    - 18080:18080
    networks:
    - yatc-frontend
    - yatc-backend
    healthcheck:
      test: "curl --fail --silent localhost:18080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    depends_on:
      yatc-redis:
        condition: service_healthy
        restart: true
      yatc-keycloak:
        condition: service_healthy
        restart: true

  ms-rest-axum:
    build: ./ms-rust-axum
    restart: no
    container_name: "ms-rest-axum"
    environment:
    - RUST_BACKTRACE=1
    - ENV_FILENAME=".env.dc"
    ports:
    - 8080:8080
    networks:
    - yatc-backend
    depends_on:
      yatc-redis:
        condition: service_healthy
        restart: true
      yatc-postgres:
        condition: service_healthy
        restart: true

  yatc-keycloak:
    image: quay.io/keycloak/keycloak:26.1
    restart: no
    container_name: "yatc-keycloak"
    environment:
    - KC_HTTP_PORT=8180
    - KC_HTTP_ENABLED=true
    - KC_HEALTH_ENABLED=true
    - KC_METRICS_ENABLED=true
    - KC_HTTP_MANAGEMENT_PORT=9000
    - KC_LOG_LEVEL=INFO
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
    - ./yatc-keycloak/realms:/opt/keycloak/data/import
    ports:
    - 8180:8180
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 5s
      timeout: 5s
      retries: 30
    command: ["start-dev", "--import-realm"]
    networks:
    - yatc-frontend

  yatc-postgres:
    image: postgres:17
    restart: no
    container_name: "yatc-postgres"
    environment:
    - POSTGRES_USER=pguser
    - POSTGRES_PASSWORD=pguser
    - POSTGRES_DB=yatc
    volumes:
    - ./yatc-postgresql/init/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
    - ./yatc-postgresql/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d yatc"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - yatc-backend

  yatc-redis:
    image: redis:7
    restart: no
    container_name: "yatc-redis"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
    - 6379:6379
    networks:
    - yatc-backend

networks: 
  yatc-frontend:
    driver: bridge
  yatc-backend:
