name: yatc-project

services:
  ms-rest-axum:
    build: ./ms-rust-axum
    restart: no
    container_name: "ms-rest-axum"
    environment:
      ENV_FILENAME: ".env.dc"
    ports:
      - 8080:8080
    networks:
      - yatc-network

  yatc-redis:
    image: redis:7
    restart: no
    container_name: "yatc-redis"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - yatc-network

networks: 
  yatc-network:
    driver: bridge
