name: yatc-project

services:
  ms-rest-axum:
    build: ./ms-rust-axum
    restart: no
    container_name: "ms-rest-axum"
    ports:
      - 8080:8080
    networks:
      - yatc-network

  yatc-postgres:
    image: postgres:17
    restart: no
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
    volumes:
      - ./yatc-postresql/init/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
      - ./yatc-postresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - yatc-network

  yatc-redis:
    image: redis:7
    restart: no
    container_name: "yatc-redis"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    networks:
      - yatc-network

networks: 
  yatc-network:
    driver: bridge
