apiVersion: v1
kind: Service
metadata:
  name: ms-python-fastapi
  labels:
    app: ms-python-fastapi
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8000'
spec:
  type: ClusterIP
  selector:
    app: ms-python-fastapi
  ports:
    - name: ms-python-fastapi
      protocol: TCP
      port: 8000
      targetPort: 8000
