# Stage 2 - Creazione immagine finale
FROM eclipse-temurin:25-jre AS final

# Impostazione timezone di default
ENV TZ="Europe/Rome"

WORKDIR /opt/app

EXPOSE 8080

ENV SPRING_JMX_ENABLED=false

COPY ./target/*.jar /opt/app/*.jar

RUN groupadd -g 2222 -r yatcusr
RUN useradd -u 2222 -g 2222 --no-log-init -r yatcusr
USER 2222:2222

ENTRYPOINT ["java", "-jar", "/opt/app/*.jar", "--spring.profiles.active=docker"]
