apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-spring-reactive
  labels:
    app: ms-spring-reactive
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ms-spring-reactive
  template:
    metadata:
      labels:
        app: ms-spring-reactive
    spec:
      containers:
      - name: ms-spring-reactive
        image: yatc/ms-spring-reactive
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 50
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: "TZ"
          value: "Europe/Rome"
