apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-spring-reactive
  labels:
    app: ms-spring-reactive
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ms-spring-reactive
  template:
    metadata:
      labels:
        app: ms-spring-reactive
    spec:
      containers:
      - name: ms-spring-reactive
        image: yatc/ms-spring-reactive
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env:
        - name: "TZ"
          value: "Europe/Rome"
