apiVersion: v1
kind: Service
metadata:
  name: fe-react-mui-exporter
  labels:
    app: fe-react-mui-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
spec:
  type: ClusterIP
  selector:
    app: fe-react-mui-exporter
  ports:
    - name: nginx-prometheus-exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
