apiVersion: v1
kind: Service
metadata:
  name: fe-react-mui
  labels:
    app: fe-react-mui
spec:
  type: ClusterIP
  selector:
    app: fe-react-mui
  ports:
    - name: fe-react-mui
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: fe-react-mui-monitor
      protocol: TCP
      port: 8080
      targetPort: 8080
