apiVersion: v1
kind: Service
metadata:
  name: gw-spring-cloud
  labels:
    app: gw-spring-cloud
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
    prometheus.io/port: '18080'
spec:
  type: ClusterIP
  selector:
    app: gw-spring-cloud
  ports:
    - name: gw-spring-cloud
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: gw-spring-cloud-monitor
      protocol: TCP
      port: 18080
      targetPort: 18080
