apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-spring-cloud
  labels:
    app: gw-spring-cloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gw-spring-cloud
  template:
    metadata:
      labels:
        app: gw-spring-cloud
    spec:
      containers:
      - name: gw-spring-cloud
        image: yatc/gw-spring-cloud
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        - containerPort: 18080
        env:
        - name: "TZ"
          value: "Europe/Rome"
