apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-mongo-exporter
  labels:
    app: yatc-mongo-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-mongo-exporter
  template:
    metadata:
      labels:
        app: yatc-mongo-exporter
    spec:
      containers:
      - name: yatc-mongo-exporter
        image: percona/mongodb_exporter:0.47.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 9216
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9216
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9216
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: "TZ"
          value: "Europe/Rome"
        - name: "MONGODB_URI"
          value: "mongodb://yatc_app:yatc_app@yatc-mongo:27017/yatc"
