apiVersion: v1
kind: Service
metadata:
  name: yatc-mongo-exporter
  labels:
    app: yatc-mongo-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9216'
spec:
  type: ClusterIP
  selector:
    app: yatc-mongo-exporter
  ports:
    - name: mongo-exporter
      protocol: TCP
      port: 9216
      targetPort: 9216
