apiVersion: v1
kind: Service
metadata:
  name: yatc-mongo
  labels:
    app: yatc-mongo
spec:
  type: ClusterIP
  selector:
    app: yatc-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
