# Build Stage
FROM node:22-alpine AS build
WORKDIR /app

RUN npm install -g @angular/cli

COPY package*.json ./
RUN npm install

COPY . .
RUN ng build --configuration production
 
# Production Stage
FROM nginx:stable-alpine AS production
COPY ./nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/fe-angular-material/browser/ /usr/share/nginx/html

EXPOSE 5001
