# Production Stage
FROM nginx:stable-alpine

COPY ./nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY ./dist/fe-angular-material/browser/. /usr/share/nginx/html/angular-material/

EXPOSE 5001

RUN addgroup -S yatcusr && adduser -S yatcusr -G yatcusr
USER yatcusr
