FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g @angular/cli

COPY package*.json /usr/src/app

RUN npm install

COPY . /usr/src/app

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "5001", "--base-href", "/angular-material/"]
