apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-node-express
  labels:
    app: ms-node-express
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ms-node-express
  template:
    metadata:
      labels:
        app: ms-node-express
    spec:
      containers:
      - name: ms-node-express
        image: yatc/ms-node-express
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 4001
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /metrics
            port: 4001
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 50
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /metrics
            port: 4001
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 4001
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: "TZ"
          value: "Europe/Rome"
