# Global configuration
global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s  # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Scrape configurations
scrape_configs:

  - job_name: "yatc-prometheus-metrics"
    static_configs:
      - targets: ["yatc-prometheus:9090"]

  - job_name: "yatc-grafana-metrics"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["yatc-grafana:3000"]

#  - job_name: "yatc-loki-metrics"
#    metrics_path: "/metrics"
#    static_configs:
#      - targets: ["yatc-loki:3100"]

  - job_name: "yatc-keycloak-metrics"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["yatc-keycloak:9000"]

  - job_name: "gw-spring-cloud-metrics"
    metrics_path: "/actuator/prometheus"  # Your application metrics endpoint
    static_configs:
      - targets: ["gw-spring-cloud:18080"]  # Replace with your application's address and port