apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yatc-ingress
spec:
  rules:
  - host: yatc-prometheus.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: yatc-prometheus
            port:
              number: 9090
  - host: yatc-grafana.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: yatc-grafana
            port:
              number: 3000
  - host: yatc-keycloak.internal
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: yatc-keycloak
            port:
              number: 8180
  defaultBackend:
    service:
      name: gw-spring-cloud
      port:
        number: 8080
