FROM apache/kafka:3.9.1

USER root
RUN mkdir -p /opt/jmx

COPY ./exporter/jmx_prometheus_javaagent*.jar /opt/jmx/jmx_prometheus_javaagent.jar
COPY ./exporter/jmx-exporter-config.yml /opt/jmx/jmx-exporter-config.yml

RUN chown -R appuser:appuser /opt/jmx 
USER appuser

ENV JMX_PORT=5555
ENV KAFKA_OPTS="-javaagent:/opt/jmx/jmx_prometheus_javaagent.jar=5556:/opt/jmx/jmx-exporter-config.yml"
