apiVersion: v1
kind: Service
metadata:
  name: yatc-kafka-exporter
  labels:
    app: yatc-kafka-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5556'
spec:
  type: ClusterIP
  selector:
    app: yatc-kafka-exporter
  ports:
    - name: kafka-exporter
      protocol: TCP
      port: 5556
      targetPort: 5556
