apiVersion: v1
kind: Service
metadata:
  name: yatc-kafka
  labels:
    app: yatc-kafka
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '5556'
spec:
  type: ClusterIP
  selector:
    app: yatc-kafka
  ports:
    - name: kafka-plaintext
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      protocol: TCP
      port: 9093
      targetPort: 9093
    - name: kafka-jmx-exporter
      protocol: TCP
      port: 5556
      targetPort: 5556
