apiVersion: v1
kind: ConfigMap
metadata:
  name: yatc-kafka-exporter-config
  labels:
    name: yatc-kafka-exporter-config
data:
  jmx-exporter-config.yml: |-
    hostPort: yatc-kafka:5555

    rules:
    - pattern: ".*"
