apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-kafka
  labels:
    app: yatc-kafka
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-kafka
  template:
    metadata:
      labels:
        app: yatc-kafka
    spec:
      hostname: yatc-kafka
      containers:
      - name: yatc-kafka
        image: apache/kafka:3.9.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 5555
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
        env:
        - name: "TZ"
          value: "Europe/Rome"
        - name: "KAFKA_AUTO_CREATE_TOPICS_ENABLE"
          value: "true"
        - name: "KAFKA_NODE_ID"
          value: "0"
        - name: "KAFKA_PROCESS_ROLES"
          value: "broker,controller"
        - name: "KAFKA_LISTENERS"
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://yatc-kafka:9092"
        - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: "KAFKA_CONTROLLER_QUORUM_VOTERS"
          value: "0@yatc-kafka:9093"
        - name: "KAFKA_CONTROLLER_LISTENER_NAMES"
          value: "CONTROLLER"
        - name: "JMX_PORT"
          value: "5555"
        - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
          value: "1"
        - name: "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS"
          value: "0"
        - name: "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR"
          value: "1"
        - name: "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR"
          value: "1"
        - name: "KAFKA_LOG_DIRS"
          value: "/tmp/kraft-combined-logs"
