apiVersion: v1
kind: Service
metadata:
  name: yatc-keycloak
  labels:
    app: yatc-keycloak
spec:
  type: ClusterIP
  selector:
    app: yatc-keycloak
  ports:
    - name: keycloak
      protocol: TCP
      port: 80
      targetPort: 80
    - name: keycloak-management
      protocol: TCP
      port: 9000
      targetPort: 9000
