apiVersion: v1
kind: Service
metadata:
  name: yatc-grafana
  labels:
    app: yatc-grafana
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '3000'
spec:
  type: ClusterIP
  selector:
    app: yatc-grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
