server:
  port: 8080
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 10s

spring:
  main:
    banner-mode: off
  application:
    name: ms-spring-servlet

---
spring.config.activate.on-profile: docker

spring:
  main:
    banner-mode: off
  application:
    name: ms-spring-servlet
