server:
  port: 8080
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 10s

spring:
  main:
    banner-mode: off
  application:
    name: ms-spring-servlet
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://yatc-keycloak/realms/yatc-realm

management:
  tracing:
    enabled: true
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: always
    info:
      access: read-only
    metrics:
      access: read-only
    prometheus:
      access: read-only
  endpoints: 
    access:
      default: none
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - prometheus

logging:
  level:
    org:
      springframework:
        kafka: DEBUG
        cloud:
          stream: DEBUG

---
spring.config.activate.on-profile: docker

spring:
  main:
    banner-mode: off
  application:
    name: ms-spring-servlet
  cloud:
    function:
      definition: testEventConsumer
    stream:
      bindings:
        testEventConsumer-in-0:
          destination: yatc-test-topic
          content-type: application/json
          group: ${spring.application.name}
        testEventProducer-out-0:
          destination: yatc-test-topic
          content-type: application/json
          producer:
            poller:
              fixed-delay: 5000
              initial-delay: 1000
      kafka:
        binder:
          brokers: yatc-kafka:9092
          auto-create-topics: true
          enable-observation: true
          transaction:
            transaction-id-prefix: yatc-kafka-tx-
          consumer-properties:
            allow:
              auto:
                create:
                  topics: true
            auto:
              offset:
                reset: earliest
            spring:
              json:
                trusted:
                  packages: "*"
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          producer-properties:
            allow:
              auto:
                create:
                  topics: true
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
          configuration:
            acks: all
