# Production Stage
FROM nginx:stable-alpine AS production

# Impostazione timezone di default
RUN apk add --no-cache tzdata
ENV TZ="Europe/Rome"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./nginx/nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY ./build /usr/share/nginx/html/react-mui

EXPOSE 3001

RUN addgroup -S yatcusr && adduser -S yatcusr -G yatcusr
USER yatcusr
