apiVersion: v1
kind: Service
metadata:
  name: yatc-loki
  labels:
    app: yatc-loki
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '3100'
spec:
  type: ClusterIP
  selector:
    app: yatc-loki
  ports:
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
