apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-loki
  labels:
    app: yatc-loki
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-loki
  template:
    metadata:
      labels:
        app: yatc-loki
    spec:
      containers:
      - name: yatc-loki
        image: grafana/loki
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3100
        env:
        - name: "TZ"
          value: "Europe/Rome"
        volumeMounts:
        - name: yatc-loki-config
          mountPath: "/etc/loki/local-config.yaml"
          subPath: "local-config.yaml"
      volumes:
      - name: yatc-loki-config
        configMap:
          name: yatc-loki-config
