server:
  port: 8080
  reactive:
    session:
      cookie:
        http-only: true
        name: "YATCSESSIONID"
      timeout: 60m
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 10s

spring:
  main:
    banner-mode: off
  application:
    name: cms-gateway-frontend
  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          default-filters:
          - RemoveRequestHeader=Cookie
          - TokenRelay
          routes:
          - id: ms-rust-axum-route
            uri: http://localhost:8081/
            predicates:
            - Path=/api/rust-axum/**
          - id: fe-angular-material-route
            uri: http://localhost:5001/
            predicates:
            - Path=/angular-material/**
          - id: fe-react-mui-route
            uri: http://localhost:3001/
            predicates:
            - Path=/react-mui/**
  session:
    timeout: 60m
    redis:
      namespace: "spring:session"
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        provider:
          yatc-keycloak:
            issuer-uri: http://yatc-keycloak:8180/realms/yatc-realm
        registration:
          keycloak-spring-gateway-client:
            provider: yatc-keycloak
            client-id: gw-spring-cloud
            client-secret: 12345678
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
  threads:
    virtual:
      enabled: true

management:
  server:
    port: 18080
  tracing:
    enabled: true
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
      show-details: always
    info:
      access: read-only
    metrics:
      access: read-only
    prometheus:
      access: read-only
  endpoints: 
    access:
      default: none
    web:
      exposure:
        include:
        - health
        - info
        - metrics
        - prometheus

logging:
  structured:
    format:
      console: logstash

---
spring.config.activate.on-profile: docker

spring:
  main:
    banner-mode: off
  application:
    name: cms-gateway-frontend
  cloud:
    gateway:
      server:
        webflux:
          metrics:
            enabled: true
          default-filters:
          - RemoveRequestHeader=Cookie
          - TokenRelay
          routes:
          - id: ms-rust-axum-route
            uri: http://ms-rust-axum:8080/
            predicates:
            - Path=/api/rust-axum/**
          - id: ms-spring-reactive-route
            uri: http://ms-spring-reactive:8080/
            predicates:
            - Path=/api/spring-reactive/**
          - id: ms-spring-servlet-route
            uri: http://ms-spring-servlet:8080/
            predicates:
            - Path=/api/spring-servlet/**
          - id: fe-angular-material-route
            uri: http://fe-angular-material:5001/
            predicates:
            - Path=/angular-material/**
          - id: fe-react-mui-route
            uri: http://fe-react-mui:3001/
            predicates:
            - Path=/react-mui/**
  session:
    timeout: 60m
    redis:
      namespace: "spring:session"
  data:
    redis:
      host: yatc-redis
      port: 6379
  security:
    oauth2:
      client:
        provider:
          yatc-keycloak:
            issuer-uri: http://yatc-keycloak/realms/yatc-realm
        registration:
          keycloak-spring-gateway-client:
            provider: yatc-keycloak
            client-id: gw-spring-cloud
            client-secret: 12345678
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
  threads:
    virtual:
      enabled: true
