apiVersion: v1
kind: PersistentVolume
metadata:
  name: yatc-poprometheusstgres-volume
  labels:
    type: local
    app: yatc-prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: ./data
