apiVersion: v1
kind: Service
metadata:
  name: yatc-prometheus
  labels:
    app: yatc-prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9090'
spec:
  type: ClusterIP
  selector:
    app: yatc-prometheus
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
