apiVersion: v1
kind: PersistentVolume
metadata:
  name: yatc-prometheus-volume
  labels:
    type: local
    app: yatc-prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/c/development/k8s/yatc/yatc-prometheus/data
