apiVersion: v1
kind: ServiceAccount
metadata:
  name: yatc-prometheus

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yatc-prometheus-discoverer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yatc-discoverer
subjects:
- kind: ServiceAccount
  name: yatc-prometheus
  namespace: default
