apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yatc-prometheus-volume-claim
  labels:
    app: yatc-prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
