apiVersion: v1
kind: Service
metadata:
  name: ms-rust-axum
  labels:
    app: ms-rust-axum
#  annotations:
#    prometheus.io/scrape: 'true'
#    prometheus.io/path: '/actuator/prometheus'
#    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  selector:
    app: ms-rust-axum
  ports:
    - name: ms-rust-axum
      protocol: TCP
      port: 8080
      targetPort: 8080
