apiVersion: v1
kind: Service
metadata:
  name: yatc-redis-exporter
  labels:
    app: yatc-redis-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '9121'
spec:
  type: ClusterIP
  selector:
    app: yatc-redis-exporter
  ports:
    - name: redis-exporter
      protocol: TCP
      port: 9121
      targetPort: 9121
