apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-redis-exporter
  labels:
    app: yatc-redis-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-redis-exporter
  template:
    metadata:
      labels:
        app: yatc-redis-exporter
    spec:
      containers:
      - name: yatc-redis-exporter
        image: oliver006/redis_exporter
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - containerPort: 9121
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: "TZ"
          value: "Europe/Rome"
        - name: REDIS_ADDR
          value: "redis://yatc-redis:6379"
