apiVersion: v1
kind: Service
metadata:
  name: yatc-dependencytrack
  labels:
    app: yatc-dependencytrack
spec:
  type: ClusterIP
  selector:
    app: yatc-dependencytrack
  ports:
    - name: dependencytrack
      protocol: TCP
      port: 8080
      targetPort: 8080
