apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatc-mongo
  labels:
    app: yatc-mongo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: yatc-mongo
  template:
    metadata:
      labels:
        app: yatc-mongo
    spec:
      containers:
      - name: yatc-mongo
        image: mongo:4.4.29
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 27017
#        livenessProbe:
#          exec:
#            command:
#              - mongosh
#              - --eval
#              - "db.adminCommand('ping')"
#          initialDelaySeconds: 30
#          timeoutSeconds: 5
#          periodSeconds: 5
#          failureThreshold: 5
#          successThreshold: 1
#        readinessProbe:
#          exec:
#            command:
#              - mongosh
#              - --eval
#              - "db.adminCommand('ping')"
#          initialDelaySeconds: 20
#          timeoutSeconds: 5
#          periodSeconds: 3
#          failureThreshold: 2
#          successThreshold: 1
        env:
        - name: TZ
          value: "Europe/Rome"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: yatc-mongo-init-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yatc-mongo-init-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: yatc-mongo-init-secret
              key: MONGO_INITDB_DATABASE
