name: Build ms-rust-axum

on:
  push:
    paths:
      - 'ms-rust-axum/**'
      - '.github/workflows/build-ms-rust-axum.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./ms-rust-axum
          file: ./ms-rust-axum/Dockerfile.multi
          tags: ghcr.io/polifr/yatc-project/ms-rust-axum:latest

          cache-from: type=gha,scope=polifr-yatc-project-ms-rust-axum
          cache-to: type=gha,mode=max,scope=polifr-yatc-project-ms-rust-axum
