name: Build ms-spring-reactive

on:
  push:
    paths:
      - 'ms-spring-reactive/**'
      - '.github/workflows/build-ms-spring-reactive.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - name: Check JDK version
      run: java --version

    - name: Cache Maven packages
      uses: actions/cache@v6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('ms-spring-reactive/**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      working-directory: ./ms-spring-reactive
      run: mvn --batch-mode --update-snapshots verify
